provider:
  name: faas-netes

# Adjust the image name to match the one you are using
faasnetes:
  image: danenherdi/faas-netes:faasflows-config-update
  enabled: true
  imagePullPolicy: Always

# Adjust the image name to match the one you are using
gateway:
  image: danenherdi/gateway:faasflows-0.2
  faasnetes:
    enabled: false

functionNamespace: openfaas-fn
basic_auth: false